#!/usr/bin/env bash
# install nginx web server and create html pages
sudo pt-get -y update
sudo apt-get install -y nginx
echo "coding school" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
